export interface QuickBooksCsvLineItem {
  description: string;
  quantity: number;
  unitPrice: number;
}

export interface QuickBooksCsvQuote {
  id: string;
  title: string;
  serviceType: string;
  status: string;
  scopeText: string;
  customerPriceSubtotal: number;
  taxAmount: number;
  totalAmount: number;
  createdAt: Date;
  sentAt?: Date | null;
  customer: {
    fullName: string;
    email?: string | null;
    phone: string;
  };
  lineItems: QuickBooksCsvLineItem[];
}

export interface BuildQuickBooksInvoiceCsvOptions {
  dueInDays?: number;
  exportedAt?: Date;
}

const QUICKBOOKS_CSV_HEADERS = [
  "Txn Type",
  "Doc Number",
  "Customer",
  "Customer Email",
  "Customer Phone",
  "Invoice Date",
  "Due Date",
  "Service Date",
  "Item Name",
  "Item Description",
  "Qty",
  "Rate",
  "Line Amount",
  "Tax Amount",
  "Invoice Total",
  "Currency",
  "Quote Title",
  "Quote ID",
  "Quote Status",
  "Internal Notes",
];

function toTwoDecimal(value: number): string {
  if (!Number.isFinite(value)) return "0.00";
  return value.toFixed(2);
}

function formatDateUtc(input: Date): string {
  const year = input.getUTCFullYear();
  const month = String(input.getUTCMonth() + 1).padStart(2, "0");
  const day = String(input.getUTCDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function addDaysUtc(input: Date, days: number): Date {
  return new Date(input.getTime() + days * 24 * 60 * 60 * 1000);
}

function csvCell(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return "";
  const raw = String(value);
  if (!/[",\n\r]/.test(raw)) return raw;
  return `"${raw.replace(/"/g, "\"\"")}"`;
}

function invoiceDocNumber(quoteId: string): string {
  const clean = quoteId.replace(/[^a-z0-9]/gi, "").toUpperCase();
  const suffix = clean.slice(-8) || "QUOTE";
  return `QF-${suffix}`;
}

function defaultLineItem(quote: QuickBooksCsvQuote): QuickBooksCsvLineItem {
  return {
    description: quote.scopeText || quote.title,
    quantity: 1,
    unitPrice: quote.customerPriceSubtotal,
  };
}

function lineItemAmount(lineItem: QuickBooksCsvLineItem): number {
  const quantity = Number.isFinite(lineItem.quantity) ? lineItem.quantity : 0;
  const rate = Number.isFinite(lineItem.unitPrice) ? lineItem.unitPrice : 0;
  return Number((quantity * rate).toFixed(2));
}

export function buildQuickBooksInvoiceCsv(
  quotes: QuickBooksCsvQuote[],
  options: BuildQuickBooksInvoiceCsvOptions = {},
): string {
  const dueInDays = Math.max(0, Math.min(365, Math.floor(options.dueInDays ?? 14)));
  const exportedAt = options.exportedAt ?? new Date();
  const rows: string[] = [QUICKBOOKS_CSV_HEADERS.map(csvCell).join(",")];

  for (const quote of quotes) {
    const invoiceDate = quote.sentAt ?? quote.createdAt;
    const dueDate = addDaysUtc(invoiceDate, dueInDays);
    const lineItems = quote.lineItems.length > 0 ? quote.lineItems : [defaultLineItem(quote)];

    for (const lineItem of lineItems) {
      const amount = lineItemAmount(lineItem);
      const columns = [
        "Invoice",
        invoiceDocNumber(quote.id),
        quote.customer.fullName,
        quote.customer.email ?? "",
        quote.customer.phone,
        formatDateUtc(invoiceDate),
        formatDateUtc(dueDate),
        formatDateUtc(quote.createdAt),
        `${quote.serviceType} Service`,
        lineItem.description,
        toTwoDecimal(lineItem.quantity),
        toTwoDecimal(lineItem.unitPrice),
        toTwoDecimal(amount),
        toTwoDecimal(quote.taxAmount),
        toTwoDecimal(quote.totalAmount),
        "USD",
        quote.title,
        quote.id,
        quote.status,
        `Generated by QuoteFly on ${formatDateUtc(exportedAt)}`,
      ];

      rows.push(columns.map(csvCell).join(","));
    }
  }

  return `${rows.join("\n")}\n`;
}
