export function quickBooksHealthFixture(overrides: Record<string, unknown> = {}) {
  return {
    schema: "quotefly.integration-health/v1",
    observedAtUtc: new Date().toISOString(),
    environment: "sandbox",
    mode: "oauth_only",
    state: "healthy",
    automation: {
      providerActionsEnabled: false,
      hostedPaymentsEnabled: false,
      reconciliationEnabled: false,
      cdcEnabled: false,
      webhookConfigured: false,
    },
    monitors: {
      bearerConfigured: true,
      apiSignalSinkConfigured: true,
      workerSignalSinkConfigured: false,
      deliveryVerified: false,
    },
    worker: {
      required: false,
      status: "not_required",
      ready: false,
      lastObservedAtUtc: null,
      releaseMatches: null,
    },
    operations: {
      webhookOutstandingCount: 0,
      webhookDeadCount: 0,
      reconciliationRequiredCount: 0,
      cdcCursorCount: 1,
      cdcTerminalCount: 0,
      cdcOverdueCount: 0,
      connectionRevocationPendingCount: 0,
      connectionRevocationDeadCount: 0,
      orphanRevocationPendingCount: 0,
      orphanRevocationDeadCount: 0,
      tokenRefreshFailureConnectionCount: 0,
      tokenRefreshReauthRequiredCount: 0,
      oldestWebhookOutstandingAgeMs: null,
      oldestReconciliationRequiredAgeMs: null,
      maximumCdcLagMs: null,
      oldestConnectionRevocationPendingAgeMs: null,
      oldestOrphanRevocationPendingAgeMs: null,
      oldestTokenRefreshFailureAgeMs: null,
    },
    ...overrides,
  };
}
